# Bank Loan Risk Analytics

## Phase 3: Data Cleaning & Business Column Selection

### Objective

The objective of this notebook is to transform the raw Lending Club dataset into a clean, business-ready dataset for downstream analytics, SQL analysis, Power BI dashboards, machine learning, and Streamlit deployment.

---

### Tasks

- Load raw dataset
- Understand dataset structure
- Analyze missing values
- Select business-relevant columns
- Clean and transform data
- Export processed datasets

## Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## Load Raw Dataset

In [5]:
df = pd.read_csv(
    "../data/raw/accepted_2007_to_2018Q4.csv",
    low_memory=False
)

## Dataset Overview

In [6]:
print(f"Shape: {df.shape}")

df.head()

Shape: (2260701, 151)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# ============================================
# Dataset Overview
# ============================================

print("="*60)
print("DATASET OVERVIEW")
print("="*60)

print(f"Rows           : {df.shape[0]:,}")
print(f"Columns        : {df.shape[1]}")
print(f"Duplicate Rows : {df.duplicated().sum():,}")

print("\nData Types")
print(df.dtypes.value_counts())

print("\nMemory Usage")
print(f"{df.memory_usage(deep=True).sum()/1024**2:.2f} MB")

============================================================
DATASET OVERVIEW
============================================================
Rows           : 2,260,701
Columns        : 151
Duplicate Rows : 0

Data Types
float64    113
str         38
Name: count, dtype: int64

Memory Usage
3138.39 MB

In [8]:
# Column names

columns = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values
})

columns

               Column Name Data Type
0                       id       str
1                member_id   float64
2                loan_amnt   float64
3              funded_amnt   float64
4          funded_amnt_inv   float64
..                     ...       ...
146      settlement_status       str
147        settlement_date       str
148      settlement_amount   float64
149  settlement_percentage   float64
150        settlement_term   float64

[151 rows x 2 columns]

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), str(38)
memory usage: 3.1 GB

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
member_id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_amnt,2260668.0,15046.931228,9190.245488,500.00,8000.00,12900.00,20000.0000,40000.00
funded_amnt,2260668.0,15041.664057,9188.413022,500.00,8000.00,12875.00,20000.0000,40000.00
funded_amnt_inv,2260668.0,15023.437745,9192.331679,0.00,8000.00,12800.00,20000.0000,40000.00
int_rate,2260668.0,13.092829,4.832138,5.31,9.49,12.62,15.9900,30.99
...,...,...,...,...,...,...,...,...
hardship_payoff_balance_amount,10917.0,11636.883942,7625.988281,55.73,5627.00,10028.39,16151.8900,40306.41
hardship_last_payment_amount,10917.0,193.994321,198.629496,0.01,44.44,133.16,284.1900,1407.86
settlement_amount,34246.0,5010.664267,3693.122590,44.21,2208.00,4146.11,6850.1725,33601.00
settlement_percentage,34246.0,47.780365,7.311822,0.20,45.00,45.00,50.0000,521.35
settlement_term,34246.0,13.191322,8.159980,0.00,6.00,14.00,18.0000,181.00

Missing Value Analysis

In [17]:
# ============================================
# Missing Value Analysis
# ============================================

missing = (
    df.isnull()
      .sum()
      .to_frame(name="Missing Values")
)

missing["Missing %"] = (
    missing["Missing Values"] / len(df) * 100
).round(2)

missing = (
    missing
    .sort_values("Missing %", ascending=False)
)

missing.head(60)

                                            Missing Values  Missing %
member_id                                          2260701     100.00
orig_projected_additional_accrued_interest         2252050      99.62
hardship_end_date                                  2249784      99.52
hardship_start_date                                2249784      99.52
hardship_type                                      2249784      99.52
hardship_reason                                    2249784      99.52
hardship_status                                    2249784      99.52
deferral_term                                      2249784      99.52
hardship_last_payment_amount                       2249784      99.52
hardship_payoff_balance_amount                     2249784      99.52
hardship_loan_status                               2249784      99.52
hardship_dpd                                       2249784      99.52
hardship_length                                    2249784      99.52
payment_plan_start_date                            2249784      99.52
hardship_amount                                    2249784      99.52
settlement_term                                    2226455      98.49
debt_settlement_flag_date                          2226455      98.49
settlement_status                                  2226455      98.49
settlement_date                                    2226455      98.49
settlement_amount                                  2226455      98.49
settlement_percentage                              2226455      98.49
sec_app_mths_since_last_major_derog                2224759      98.41
sec_app_revol_util                                 2154517      95.30
sec_app_mort_acc                                   2152680      95.22
revol_bal_joint                                    2152681      95.22
sec_app_fico_range_low                             2152680      95.22
sec_app_fico_range_high                            2152680      95.22
sec_app_earliest_cr_line                           2152680      95.22
sec_app_inq_last_6mths                             2152680      95.22
sec_app_open_acc                                   2152680      95.22
sec_app_open_act_il                                2152680      95.22
sec_app_num_rev_accts                              2152680      95.22
sec_app_chargeoff_within_12_mths                   2152680      95.22
sec_app_collections_12_mths_ex_med                 2152680      95.22
verification_status_joint                          2144971      94.88
dti_joint                                          2139995      94.66
annual_inc_joint                                   2139991      94.66
desc                                               2134636      94.42
mths_since_last_record                             1901545      84.11
mths_since_recent_bc_dlq                           1741000      77.01
mths_since_last_major_derog                        1679926      74.31
mths_since_recent_revol_delinq                     1520342      67.25
next_pymnt_d                                       1345343      59.51
mths_since_last_delinq                             1158535      51.25
il_util                                            1068883      47.28
mths_since_rcnt_il                                  909957      40.25
all_util                                            866381      38.32
open_rv_24m                                         866162      38.31
open_rv_12m                                         866162      38.31
total_bal_il                                        866162      38.31
open_il_24m                                         866162      38.31
open_il_12m                                         866162      38.31
open_act_il                                         866162      38.31
open_acc_6m                                         866163      38.31
total_cu_tl                                         866163      38.31
inq_last_12m                                        866163      38.31
max_bal_bc                                          866162      38.31
inq_fi                                              866162      38.31
mths_since_recent_inq                               295468      13.07
emp_title                                           167002       7.39

In [18]:
# ============================================
# Unique Values
# ============================================

unique = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": df.nunique().values
})

unique.sort_values(
    "Unique Values",
    ascending=True
).head(30)

                         Column  Unique Values
1                     member_id              0
55                  policy_code              1
129               hardship_type              1
132               deferral_term              1
137             hardship_length              1
128               hardship_flag              2
144        debt_settlement_flag              2
143         disbursement_method              2
5                          term              2
56             application_type              2
37          initial_list_status              2
17                   pymnt_plan              2
131             hardship_status              3
14          verification_status              3
59    verification_status_joint              3
146           settlement_status              3
139        hardship_loan_status              5
104                num_tl_30dpd              5
12               home_ownership              6
8                         grade              7
103            num_tl_120dpd_2m              7
119      sec_app_inq_last_6mths              7
16                  loan_status              9
130             hardship_reason              9
60               acc_now_delinq              9
82     chargeoff_within_12_mths             11
11                   emp_length             11
109        pub_rec_bankruptcies             12
20                      purpose             14
53   collections_12_mths_ex_med             16

In [19]:
# ============================================
# Final Business Columns
# ============================================

selected_columns = [

    # Loan Information
    "loan_amnt",
    "term",
    "int_rate",
    "installment",
    "grade",
    "sub_grade",
    "purpose",
    "loan_status",
    "issue_d",

    # Customer Information
    "annual_inc",
    "emp_length",
    "home_ownership",
    "verification_status",

    # Credit Profile
    "fico_range_low",
    "fico_range_high",
    "dti",
    "open_acc",
    "pub_rec",
    "revol_bal",
    "revol_util",
    "total_acc",
    "delinq_2yrs",
    "inq_last_6mths",

    # Additional Financial Features
    "earliest_cr_line",
    "mort_acc",
    "tot_cur_bal",
    "total_bc_limit",
    "tot_hi_cred_lim",

    # Location
    "addr_state",

    # Application
    "application_type"
]

len(selected_columns)

30

In [20]:
# ============================================
# Create Selected Dataset
# ============================================

df_selected = df[selected_columns].copy()

print(df_selected.shape)

df_selected.head()

(2260701, 30)

,loan_amnt,term,int_rate,installment,grade,sub_grade,purpose,loan_status,issue_d,annual_inc,emp_length,home_ownership,verification_status,fico_range_low,fico_range_high,dti,open_acc,pub_rec,revol_bal,revol_util,total_acc,delinq_2yrs,inq_last_6mths,earliest_cr_line,mort_acc,tot_cur_bal,total_bc_limit,tot_hi_cred_lim,addr_state,application_type
0,3600.0,36 months,13.99,123.03,C,C4,debt_consolidation,Fully Paid,Dec-2015,55000.0,10+ years,MORTGAGE,Not Verified,675.0,679.0,5.91,7.0,0.0,2765.0,29.7,13.0,0.0,1.0,Aug-2003,1.0,144904.0,2400.0,178050.0,PA,Individual
1,24700.0,36 months,11.99,820.28,C,C1,small_business,Fully Paid,Dec-2015,65000.0,10+ years,MORTGAGE,Not Verified,715.0,719.0,16.06,22.0,0.0,21470.0,19.2,38.0,1.0,4.0,Dec-1999,4.0,204396.0,79300.0,314017.0,SD,Individual
2,20000.0,60 months,10.78,432.66,B,B4,home_improvement,Fully Paid,Dec-2015,63000.0,10+ years,MORTGAGE,Not Verified,695.0,699.0,10.78,6.0,0.0,7869.0,56.2,18.0,0.0,0.0,Aug-2000,5.0,189699.0,6200.0,218418.0,IL,Joint App
3,35000.0,60 months,14.85,829.90,C,C5,debt_consolidation,Current,Dec-2015,110000.0,10+ years,MORTGAGE,Source Verified,785.0,789.0,17.06,13.0,0.0,7802.0,11.6,17.0,0.0,0.0,Sep-2008,1.0,301500.0,62500.0,381215.0,NJ,Individual
4,10400.0,60 months,22.45,289.91,F,F1,major_purchase,Fully Paid,Dec-2015,104433.0,3 years,MORTGAGE,Source Verified,695.0,699.0,25.37,12.0,0.0,21929.0,64.5,35.0,1.0,3.0,Jun-1998,6.0,331730.0,20300.0,439570.0,PA,Individual

In [21]:
# ============================================
# Save Selected Dataset
# ============================================

output_path = "../data/processed/lending_club_selected_columns.csv"

df_selected.to_csv(
    output_path,
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!

In [22]:
print(
    f"Memory Usage: "
    f"{df_selected.memory_usage(deep=True).sum()/1024**2:.2f} MB"
)

Memory Usage: 714.68 MB

In [23]:
df_selected.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 30 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 str
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   purpose              str
 7   loan_status          str
 8   issue_d              str
 9   annual_inc           float64
 10  emp_length           str
 11  home_ownership       str
 12  verification_status  str
 13  fico_range_low       float64
 14  fico_range_high      float64
 15  dti                  float64
 16  open_acc             float64
 17  pub_rec              float64
 18  revol_bal            float64
 19  revol_util           float64
 20  total_acc            float64
 21  delinq_2yrs          float64
 22  inq_last_6mths       float64
 23  earliest_cr_line     str
 24  mort_acc             float64
 25  tot_cur_bal          float64
 26  total_bc_limit       float64
 27  tot_hi_cred_lim      float64
 28  addr_state           str
 29  application_type     str
dtypes: float64(18), str(12)
memory usage: 714.7 MB

In [28]:
df_selected.dtypes

loan_amnt              float64
term                       str
int_rate               float64
installment            float64
grade                      str
sub_grade                  str
loan_status                str
purpose                    str
issue_d                    str
annual_inc             float64
emp_length                 str
home_ownership             str
verification_status        str
fico_range_low         float64
fico_range_high        float64
dti                    float64
open_acc               float64
pub_rec                float64
revol_bal              float64
revol_util             float64
total_acc              float64
delinq_2yrs            float64
inq_last_6mths         float64
earliest_cr_line           str
mort_acc               float64
tot_cur_bal            float64
total_bc_limit         float64
tot_hi_cred_lim        float64
addr_state                 str
application_type           str
dtype: object

In [30]:
df_selected["term"] = (
    df_selected["term"]
    .str.replace(" months", "", regex=False)
)

df_selected["term"] = pd.to_numeric(
    df_selected["term"],
    errors="coerce"
)

In [31]:
percentage_columns = [
    "int_rate",
    "revol_util"
]

for col in percentage_columns:
    df_selected[col] = (
        df_selected[col]
        .astype(str)
        .str.replace("%", "", regex=False)
    )

    df_selected[col] = pd.to_numeric(
        df_selected[col],
        errors="coerce"
    )

In [32]:
date_columns = [
    "issue_d",
    "earliest_cr_line"
]

for col in date_columns:
    df_selected[col] = pd.to_datetime(
        df_selected[col],
        format="%b-%Y",
        errors="coerce"
    )

In [33]:
df_selected.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 30 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 float64
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   loan_status          str
 7   purpose              str
 8   issue_d              datetime64[us]
 9   annual_inc           float64
 10  emp_length           str
 11  home_ownership       str
 12  verification_status  str
 13  fico_range_low       float64
 14  fico_range_high      float64
 15  dti                  float64
 16  open_acc             float64
 17  pub_rec              float64
 18  revol_bal            float64
 19  revol_util           float64
 20  total_acc            float64
 21  delinq_2yrs          float64
 22  inq_last_6mths       float64
 23  earliest_cr_line     datetime64[us]
 24  mort_acc             float64
 25  tot_cur_bal          float64
 26  total_bc_limit       float64
 27  tot_hi_cred_lim      float64
 28  addr_state           str
 29  application_type     str
dtypes: datetime64[us](2), float64(19), str(9)
memory usage: 657.8 MB

In [34]:
df_selected.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,loan_status,purpose,issue_d,annual_inc,emp_length,home_ownership,verification_status,fico_range_low,fico_range_high,dti,open_acc,pub_rec,revol_bal,revol_util,total_acc,delinq_2yrs,inq_last_6mths,earliest_cr_line,mort_acc,tot_cur_bal,total_bc_limit,tot_hi_cred_lim,addr_state,application_type
0,3600.0,36.0,13.99,123.03,C,C4,Fully Paid,debt_consolidation,2015-12-01,55000.0,10+ years,MORTGAGE,Not Verified,675.0,679.0,5.91,7.0,0.0,2765.0,29.7,13.0,0.0,1.0,2003-08-01,1.0,144904.0,2400.0,178050.0,PA,Individual
1,24700.0,36.0,11.99,820.28,C,C1,Fully Paid,small_business,2015-12-01,65000.0,10+ years,MORTGAGE,Not Verified,715.0,719.0,16.06,22.0,0.0,21470.0,19.2,38.0,1.0,4.0,1999-12-01,4.0,204396.0,79300.0,314017.0,SD,Individual
2,20000.0,60.0,10.78,432.66,B,B4,Fully Paid,home_improvement,2015-12-01,63000.0,10+ years,MORTGAGE,Not Verified,695.0,699.0,10.78,6.0,0.0,7869.0,56.2,18.0,0.0,0.0,2000-08-01,5.0,189699.0,6200.0,218418.0,IL,Joint App
3,35000.0,60.0,14.85,829.90,C,C5,Current,debt_consolidation,2015-12-01,110000.0,10+ years,MORTGAGE,Source Verified,785.0,789.0,17.06,13.0,0.0,7802.0,11.6,17.0,0.0,0.0,2008-09-01,1.0,301500.0,62500.0,381215.0,NJ,Individual
4,10400.0,60.0,22.45,289.91,F,F1,Fully Paid,major_purchase,2015-12-01,104433.0,3 years,MORTGAGE,Source Verified,695.0,699.0,25.37,12.0,0.0,21929.0,64.5,35.0,1.0,3.0,1998-06-01,6.0,331730.0,20300.0,439570.0,PA,Individual

In [35]:
df_selected["term"].isna().sum()

np.int64(33)

In [36]:
df_selected["term"].value_counts(dropna=False)

term
36.0    1609754
60.0     650914
NaN          33
Name: count, dtype: int64

In [37]:
# ============================================
# Missing Values in Selected Dataset
# ============================================

missing = (
    df_selected.isnull()
    .sum()
    .to_frame("Missing Values")
)

missing["Missing %"] = (
    missing["Missing Values"] / len(df_selected) * 100
).round(2)

missing = missing[missing["Missing Values"] > 0]

missing.sort_values("Missing %", ascending=False)

                     Missing Values  Missing %
emp_length                   146940       6.50
tot_hi_cred_lim               70309       3.11
tot_cur_bal                   70309       3.11
total_bc_limit                50063       2.21
mort_acc                      50063       2.21
dti                            1744       0.08
revol_util                     1835       0.08
open_acc                         62       0.00
addr_state                       33       0.00
earliest_cr_line                 62       0.00
inq_last_6mths                   63       0.00
delinq_2yrs                      62       0.00
total_acc                        62       0.00
revol_bal                        33       0.00
pub_rec                          62       0.00
loan_amnt                        33       0.00
term                             33       0.00
fico_range_high                  33       0.00
fico_range_low                   33       0.00
verification_status              33       0.00
home_ownership                   33       0.00
annual_inc                       37       0.00
issue_d                          33       0.00
purpose                          33       0.00
loan_status                      33       0.00
sub_grade                        33       0.00
grade                            33       0.00
installment                      33       0.00
int_rate                         33       0.00
application_type                 33       0.00

In [38]:
# ============================================
# Handle Missing Values
# ============================================

# Fill categorical column
df_selected["emp_length"] = df_selected["emp_length"].fillna("Unknown")

# Fill numerical columns with median
median_columns = [
    "tot_hi_cred_lim",
    "tot_cur_bal",
    "total_bc_limit",
    "mort_acc",
    "dti",
    "revol_util"
]

for col in median_columns:
    df_selected[col] = df_selected[col].fillna(
        df_selected[col].median()
    )

# Remove remaining rows with missing values
df_selected.dropna(inplace=True)

print(df_selected.shape)

(2260638, 30)

In [39]:
df_selected.isnull().sum().sum()

np.int64(0)

In [40]:
df_selected.to_csv(
    "../data/processed/lending_club_clean.csv",
    index=False
)

print("✅ lending_club_clean.csv saved successfully!")

✅ lending_club_clean.csv saved successfully!

In [42]:
df_selected.info()

<class 'pandas.DataFrame'>
Index: 2260638 entries, 0 to 2260698
Data columns (total 30 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            float64
 1   term                 float64
 2   int_rate             float64
 3   installment          float64
 4   grade                str
 5   sub_grade            str
 6   loan_status          str
 7   purpose              str
 8   issue_d              datetime64[us]
 9   annual_inc           float64
 10  emp_length           str
 11  home_ownership       str
 12  verification_status  str
 13  fico_range_low       float64
 14  fico_range_high      float64
 15  dti                  float64
 16  open_acc             float64
 17  pub_rec              float64
 18  revol_bal            float64
 19  revol_util           float64
 20  total_acc            float64
 21  delinq_2yrs          float64
 22  inq_last_6mths       float64
 23  earliest_cr_line     datetime64[us]
 24  mort_acc             float64
 25  tot_cur_bal          float64
 26  total_bc_limit       float64
 27  tot_hi_cred_lim      float64
 28  addr_state           str
 29  application_type     str
dtypes: datetime64[us](2), float64(19), str(9)
memory usage: 676.0 MB

In [43]:
print("=" * 50)
print("FINAL CLEAN DATASET")
print("=" * 50)

print(f"Rows    : {df_selected.shape[0]:,}")
print(f"Columns : {df_selected.shape[1]}")

==================================================
FINAL CLEAN DATASET
==================================================
Rows    : 2,260,638
Columns : 30

In [44]:
print("Total Missing Values:", df_selected.isnull().sum().sum())

Total Missing Values: 0

In [45]:
print("Duplicate Rows:", df_selected.duplicated().sum())

Duplicate Rows: 0

In [46]:
df_selected.dtypes

loan_amnt                     float64
term                          float64
int_rate                      float64
installment                   float64
grade                             str
sub_grade                         str
loan_status                       str
purpose                           str
issue_d                datetime64[us]
annual_inc                    float64
emp_length                        str
home_ownership                    str
verification_status               str
fico_range_low                float64
fico_range_high               float64
dti                           float64
open_acc                      float64
pub_rec                       float64
revol_bal                     float64
revol_util                    float64
total_acc                     float64
delinq_2yrs                   float64
inq_last_6mths                float64
earliest_cr_line       datetime64[us]
mort_acc                      float64
tot_cur_bal                   float64
total_bc_limit                float64
tot_hi_cred_lim               float64
addr_state                        str
application_type                  str
dtype: object

In [47]:
# ============================================
# Create Target Variable
# ============================================

default_status = [
    "Charged Off",
    "Default",
    "Late (31-120 days)",
    "Late (16-30 days)"
]

df_selected["default_flag"] = (
    df_selected["loan_status"]
    .isin(default_status)
    .astype(int)
)

In [48]:
df_selected["default_flag"].value_counts()

default_flag
0    1966223
1     294415
Name: count, dtype: int64

In [49]:
round(
    df_selected["default_flag"]
    .value_counts(normalize=True) * 100,
    2
)

default_flag
0    86.98
1    13.02
Name: proportion, dtype: float64

In [50]:
df_selected.to_csv(
    "../data/processed/lending_club_clean.csv",
    index=False
)

print("✅ Clean dataset exported successfully.")

✅ Clean dataset exported successfully.

In [57]:
from sklearn.model_selection import train_test_split

df_sample, _ = train_test_split(
    df_selected,
    train_size=150000,
    stratify=df_selected["default_flag"],
    random_state=42
)

print(df_sample.shape)

(150000, 31)

In [58]:
df_sample.to_csv(
    "../data/processed/lending_club_sample.csv",
    index=False
)

In [59]:
print(df_selected.shape)
print(df_sample.shape)

(2260638, 31)
(150000, 31)

(2110638, 31)

# Feature Engineering.

## Feature 1: Credit Score

In [60]:
# ============================================
# Feature 1: Credit Score
# ============================================

df_selected["credit_score"] = (
    (
        df_selected["fico_range_low"] +
        df_selected["fico_range_high"]
    ) / 2
)

df_selected["credit_score"].describe()

count    2.260638e+06
mean     7.005879e+02
std      3.301043e+01
min      6.120000e+02
25%      6.770000e+02
50%      6.920000e+02
75%      7.170000e+02
max      8.475000e+02
Name: credit_score, dtype: float64

## Feature 2: Income Group

In [61]:
# ============================================
# Feature 2: Income Group
# ============================================

income_bins = [
    0,
    50000,
    100000,
    200000,
    float("inf")
]

income_labels = [
    "Low",
    "Middle",
    "High",
    "Very High"
]

df_selected["income_group"] = pd.cut(
    df_selected["annual_inc"],
    bins=income_bins,
    labels=income_labels
)

df_selected["income_group"].value_counts()

income_group
Middle       1098847
Low           712977
High          393756
Very High      53391
Name: count, dtype: int64

## Feature 3: Loan Amount Group

In [62]:
loan_bins = [
    0,
    5000,
    15000,
    30000,
    float("inf")
]

loan_labels = [
    "Small",
    "Medium",
    "Large",
    "Very Large"
]

df_selected["loan_amount_group"] = pd.cut(
    df_selected["loan_amnt"],
    bins=loan_bins,
    labels=loan_labels
)

df_selected["loan_amount_group"].value_counts()

loan_amount_group
Medium        1060915
Large          729542
Small          299349
Very Large     170832
Name: count, dtype: int64

## Feature 4: Interest Rate Group

In [63]:
rate_bins = [
    0,
    8,
    13,
    18,
    float("inf")
]

rate_labels = [
    "Low",
    "Moderate",
    "High",
    "Very High"
]

df_selected["interest_rate_group"] = pd.cut(
    df_selected["int_rate"],
    bins=rate_bins,
    labels=rate_labels
)

df_selected["interest_rate_group"].value_counts()

interest_rate_group
Moderate     849515
High         692625
Low          382205
Very High    336293
Name: count, dtype: int64

## Feature 5: Issue Year

In [64]:
df_selected["issue_year"] = (
    df_selected["issue_d"]
    .dt.year
)

df_selected["issue_year"].value_counts().sort_index()

issue_year
2007       574
2008      2393
2009      5281
2010     12537
2011     21721
2012     53367
2013    134814
2014    235629
2015    421095
2016    434406
2017    443579
2018    495242
Name: count, dtype: int64

In [65]:
new_features = [
    "credit_score",
    "income_group",
    "loan_amount_group",
    "interest_rate_group",
    "issue_year"
]

df_selected[new_features].head()

   credit_score income_group loan_amount_group interest_rate_group  issue_year
0         677.0       Middle             Small                High        2015
1         717.0       Middle             Large            Moderate        2015
2         697.0       Middle             Large            Moderate        2015
3         787.0         High        Very Large                High        2015
4         697.0         High            Medium           Very High        2015

In [66]:
df_selected.to_csv(
    "../data/processed/lending_club_clean.csv",
    index=False
)

print("✅ Feature engineered dataset saved successfully!")

✅ Feature engineered dataset saved successfully!

In [67]:
df_selected[new_features].head()

   credit_score income_group loan_amount_group interest_rate_group  issue_year
0         677.0       Middle             Small                High        2015
1         717.0       Middle             Large            Moderate        2015
2         697.0       Middle             Large            Moderate        2015
3         787.0         High        Very Large                High        2015
4         697.0         High            Medium           Very High        2015

In [68]:
df_selected.shape

(2260638, 36)